/**
 * Tenant isolation regression tests.
 *
 * These tests verify that:
 * 1. All data-fetching hooks require an active org_id before querying
 * 2. All mutations include org_id in inserts
 * 3. Audit log writes include org_id
 * 4. ResetDataModal scopes all operations to the current org
 * 5. Org-switching clears cached state
 *
 * These are pure-logic / structural tests — no DB connection required.
 */

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'fs'
import { resolve } from 'path'

const ROOT = resolve(__dirname, '../../..')
const src  = (rel: string) => readFileSync(resolve(ROOT, 'src', rel), 'utf-8')

// ── Audit log ─────────────────────────────────────────────────────────────────

describe('useAuditLog tenant isolation', () => {
  const code = src('hooks/useAuditLog.ts')

  it('imports useOrgStore', () => {
    expect(code).toContain("from '../store/orgStore'")
  })

  it('reads orgId from store', () => {
    expect(code).toContain('useOrgStore')
    expect(code).toContain('orgId')
  })

  it('guards fetch on orgId presence', () => {
    expect(code).toContain('if (!orgId)')
  })

  it('filters audit_log query by org_id', () => {
    expect(code).toContain(".eq('org_id', orgId)")
  })

  it('includes orgId in useCallback deps', () => {
    expect(code).toMatch(/useCallback\(.*orgId.*\[orgId/s)
  })
})

// ── Field changes ─────────────────────────────────────────────────────────────

describe('useFieldChanges tenant isolation', () => {
  const code = src('hooks/useFieldChanges.ts')

  it('imports useOrgStore', () => {
    expect(code).toContain("from '../store/orgStore'")
  })

  it('reads orgId from store', () => {
    expect(code).toContain('useOrgStore')
    expect(code).toContain('orgId')
  })

  it('guards fetch on orgId presence', () => {
    expect(code).toContain('if (!orgId)')
  })

  it('filters field_changes query by org_id', () => {
    expect(code).toContain(".eq('org_id', orgId)")
  })

  it('includes orgId in useCallback deps', () => {
    expect(code).toContain('[orgId,')
  })
})

// ── Mutations: audit functions are no-ops (LB-9) ─────────────────────────────
// Audit writes are now generated by server-side DB triggers so clients cannot
// forge user_id, old_data, new_data, or timestamps.

describe('useMutations audit functions are no-ops', () => {
  const code = src('hooks/useMutations.ts')

  it('logAudit body is empty (no DB insert)', () => {
    const start = code.indexOf('async function logAudit')
    const end   = code.indexOf('async function batchLogAudit')
    const body  = code.slice(start, end)
    expect(body).not.toContain("supabase.from('audit_log')")
  })

  it('logFieldChanges body is empty (no DB insert)', () => {
    const start = code.indexOf('async function logFieldChanges')
    const end   = code.indexOf('async function logAudit')
    const body  = code.slice(start, end)
    expect(body).not.toContain("supabase.from('field_changes')")
  })

  it('batchLogAudit body is empty (no DB insert)', () => {
    const start = code.indexOf('async function batchLogAudit')
    const end   = code.indexOf('async function batchLogFieldChanges')
    const body  = code.slice(start, end)
    expect(body).not.toContain("supabase.from('audit_log')")
  })

  it('batchLogFieldChanges body is empty (no DB insert)', () => {
    const start = code.indexOf('async function batchLogFieldChanges')
    const end   = code.indexOf('// ── Input types')
    const body  = code.slice(start, end)
    expect(body).not.toContain("supabase.from('field_changes')")
  })
})

// ── Migration: server-side audit triggers (LB-9) ─────────────────────────────

describe('security migration: server-side audit triggers', () => {
  const migration = readFileSync(
    resolve(ROOT, 'supabase/migrations/20260605000001_server_side_audit_triggers.sql'),
    'utf-8',
  )

  it('creates audit_trigger_fn as SECURITY DEFINER', () => {
    expect(migration).toContain('CREATE OR REPLACE FUNCTION public.audit_trigger_fn()')
    expect(migration).toContain('SECURITY DEFINER')
    expect(migration).toContain('auth.uid()')
  })

  it('creates field_changes_trigger_fn as SECURITY DEFINER', () => {
    expect(migration).toContain('CREATE OR REPLACE FUNCTION public.field_changes_trigger_fn()')
    expect(migration).toContain('SECURITY DEFINER')
  })

  it('attaches audit trigger to inflow_transactions', () => {
    expect(migration).toContain('trg_audit_inflow_transactions')
    expect(migration).toContain('AFTER INSERT OR UPDATE OR DELETE ON public.inflow_transactions')
  })

  it('attaches audit trigger to outflow_transactions', () => {
    expect(migration).toContain('trg_audit_outflow_transactions')
    expect(migration).toContain('AFTER INSERT OR UPDATE OR DELETE ON public.outflow_transactions')
  })

  it('attaches field-change trigger to inflow_transactions', () => {
    expect(migration).toContain('trg_field_changes_inflow_transactions')
    expect(migration).toContain('AFTER UPDATE ON public.inflow_transactions')
  })

  it('drops client audit_insert policy', () => {
    expect(migration).toContain('DROP POLICY IF EXISTS "audit_insert"')
  })

  it('drops client field_changes_insert policy', () => {
    expect(migration).toContain('DROP POLICY IF EXISTS "field_changes_insert"')
  })

  it('trigger function uses TG_OP and TG_TABLE_NAME (not client-supplied)', () => {
    expect(migration).toContain('TG_OP')
    expect(migration).toContain('TG_TABLE_NAME')
  })

  it('trigger function uses SET search_path guard', () => {
    expect(migration).toContain('SET search_path = public')
  })
})

// ── ResetDataModal: export and delete scoping ─────────────────────────────────

describe('ResetDataModal tenant isolation', () => {
  const code = src('components/modals/ResetDataModal.tsx')

  it('imports useOrgStore', () => {
    expect(code).toContain("from '../../store/orgStore'")
  })

  it('Q helper includes org_id filter', () => {
    expect(code).toContain('.eq(\'org_id\', orgId)')
  })

  it('runExport accepts orgId parameter', () => {
    expect(code).toContain('async function runExport(key: string, sym: string, orgId: string)')
  })

  it('deleteAllData accepts orgId parameter', () => {
    expect(code).toContain('async function deleteAllData(orgId: string)')
  })

  it('deleteAllData scopes receipts select by org_id', () => {
    const deleteSection = code.slice(
      code.indexOf('async function deleteAllData'),
      code.indexOf('// ── Component'),
    )
    expect(deleteSection).toContain('.eq(\'org_id\', orgId)')
  })

  it('deleteAllData scopes table deletes by org_id', () => {
    const deleteSection = code.slice(
      code.indexOf('async function deleteAllData'),
      code.indexOf('// ── Component'),
    )
    expect(deleteSection).toContain('.delete().eq(\'org_id\', orgId)')
  })

  it('handleDelete guards on orgId', () => {
    expect(code).toContain('if (!orgId) return')
  })

  it('audit-log export filters by org_id', () => {
    const auditSection = code.slice(
      code.indexOf("key === 'audit-log'"),
      code.indexOf("key === 'audit-log'") + 400,
    )
    expect(auditSection).toContain(".eq('org_id', orgId)")
  })
})

// ── All data hooks guard on orgId ─────────────────────────────────────────────

describe('all data hooks guard before querying', () => {
  const hooks = [
    'hooks/useBanks.ts',
    'hooks/useCategories.ts',
    'hooks/useDashboard.ts',
    'hooks/useDepartments.ts',
    'hooks/useDynamicReports.ts',
    'hooks/useFX.ts',
    'hooks/useFXConversions.ts',
    'hooks/useIncomeTypes.ts',
    'hooks/useLedger.ts',
    'hooks/useOutflowTypes.ts',
    'hooks/useReportEngine.ts',
    'hooks/useReportTemplates.ts',
    'hooks/useAuditLog.ts',
    'hooks/useFieldChanges.ts',
  ]

  hooks.forEach(hook => {
    it(`${hook} checks orgId before fetching`, () => {
      const code = src(hook)
      expect(code).toContain('orgId')
      // Guard pattern: `if (!orgId)` or combined `if (!x || !orgId)` or `if (!orgId ||`
      expect(code).toMatch(/if \(!orgId\)|if \(![^)]+\|\|\s*!orgId\)|if \(!orgId\s*\|\|/)
    })
  })
})

// ── Org-switching clears all caches ──────────────────────────────────────────

describe('org switching cache invalidation', () => {
  const authCode = src('hooks/useAuth.ts')

  it('switchOrg resets allocation store', () => {
    const switchSection = authCode.slice(
      authCode.indexOf('const switchOrg'),
      authCode.indexOf('return { switchOrg }'),
    )
    expect(switchSection).toContain('useAllocationStore.getState().reset()')
  })

  it('switchOrg resets account codes store', () => {
    const switchSection = authCode.slice(
      authCode.indexOf('const switchOrg'),
      authCode.indexOf('return { switchOrg }'),
    )
    expect(switchSection).toContain('useAccountCodesStore.getState().reset()')
  })

  it('signOut clears org state', () => {
    const signOutSection = authCode.slice(
      authCode.indexOf('const signOut'),
      authCode.indexOf('return {') + 200,
    )
    expect(signOutSection).toContain('useOrgStore.getState().clearOrg()')
  })
})

// ── Migration: audit_log and field_changes get org_id ────────────────────────

describe('security migration: audit log org isolation', () => {
  const migration = readFileSync(
    resolve(ROOT, 'supabase/migrations/20260602000003_audit_log_org_isolation.sql'),
    'utf-8',
  )

  it('adds org_id to audit_log', () => {
    expect(migration).toContain('ALTER TABLE public.audit_log')
    expect(migration).toContain('ADD COLUMN IF NOT EXISTS org_id')
  })

  it('adds org_id to field_changes', () => {
    expect(migration).toContain('ALTER TABLE public.field_changes')
    expect(migration).toContain('ADD COLUMN IF NOT EXISTS org_id')
  })

  it('drops old cross-org is_admin() SELECT policy', () => {
    expect(migration).toContain("DROP POLICY IF EXISTS \"audit_admin_read\"")
  })

  it('replaces audit_log SELECT with org-scoped policy', () => {
    expect(migration).toContain('CREATE POLICY "audit_select" ON public.audit_log')
    expect(migration).toContain('is_org_member(org_id)')
  })

  it('replaces field_changes SELECT with org-scoped policy', () => {
    expect(migration).toContain('CREATE POLICY "field_changes_select" ON public.field_changes')
    expect(migration).toContain('is_org_member(org_id)')
  })

  it('adds DELETE policy so org admins can clear own logs', () => {
    expect(migration).toContain('CREATE POLICY "audit_delete" ON public.audit_log')
    expect(migration).toContain('CREATE POLICY "field_changes_delete" ON public.field_changes')
  })

  it('fixes profiles_update_admin cross-org leak', () => {
    expect(migration).toContain("DROP POLICY IF EXISTS \"profiles_update_admin\"")
    expect(migration).toContain('CREATE POLICY "profiles_update_admin" ON public.profiles')
    // New policy must use org-scoped join, not the global is_admin()
    expect(migration).toContain('org_members caller')
    expect(migration).toContain('JOIN   public.org_members target')
  })

  it('fixes profiles_delete cross-org leak', () => {
    expect(migration).toContain("DROP POLICY IF EXISTS \"profiles_delete\"")
    expect(migration).toContain('CREATE POLICY "profiles_delete" ON public.profiles')
  })

  it('backfills audit_log org_id for existing rows', () => {
    expect(migration).toContain('UPDATE public.audit_log')
    expect(migration).toContain('SET    org_id = COALESCE')
  })

  it('backfills field_changes org_id for existing rows', () => {
    expect(migration).toContain('UPDATE public.field_changes')
    expect(migration).toContain('SET    org_id = COALESCE')
  })
})

// ── Storage: receipt file paths include org prefix ────────────────────────────

describe('useReceipts storage org isolation', () => {
  const code = src('hooks/useReceipts.ts')

  it('upload path uses org prefix {orgId}/{entityType}/{entityId}/...', () => {
    expect(code).toContain('`${currentOrgId}/${entityType}/${entityId}/')
  })

  it('upload throws when no active org', () => {
    expect(code).toContain("if (!currentOrgId) throw new Error('No active organisation.')")
  })

  it('upload always sets org_id in DB insert', () => {
    const uploadSection = code.slice(
      code.indexOf('const upload = useCallback'),
      code.indexOf('const remove = useCallback'),
    )
    expect(uploadSection).toContain('org_id:      currentOrgId')
    expect(uploadSection).not.toContain('...(orgId ?')
  })

  it('per-entity fetch adds org_id filter when available', () => {
    const fetchSection = code.slice(
      code.indexOf('const fetch = useCallback'),
      code.indexOf('const upload = useCallback'),
    )
    expect(fetchSection).toContain(".eq('org_id', orgId)")
  })
})

// ── Storage: migration hardens bucket policies ────────────────────────────────

describe('storage isolation migration', () => {
  const migration = readFileSync(
    resolve(ROOT, 'supabase/migrations/20260602000005_storage_org_isolation.sql'),
    'utf-8',
  )

  it('sets receipts bucket to private (not public)', () => {
    expect(migration).toContain("'receipts', false")
  })

  it('sets backups bucket to private', () => {
    expect(migration).toContain("'backups', false")
  })

  it('drops old permissive receipts storage policies', () => {
    expect(migration).toContain("DROP POLICY IF EXISTS \"receipts_objects_insert\"")
    expect(migration).toContain("DROP POLICY IF EXISTS \"receipts_objects_select\"")
  })

  it('new receipts INSERT checks org membership via path prefix', () => {
    const insertSection = migration.slice(
      migration.indexOf('receipts_storage_insert'),
      migration.indexOf('receipts_storage_select'),
    )
    expect(insertSection).toContain('is_org_member')
    expect(insertSection).toContain('is_org_finance_user')
    expect(insertSection).toContain('storage.foldername(name)')
  })

  it('new receipts SELECT checks org membership via path prefix', () => {
    const selectSection = migration.slice(
      migration.indexOf('receipts_storage_select'),
      migration.indexOf('receipts_storage_delete'),
    )
    expect(selectSection).toContain('is_org_member')
    expect(selectSection).toContain('storage.foldername(name)')
  })

  it('backups INSERT enforces caller-owned path prefix', () => {
    const insertSection = migration.slice(
      migration.indexOf('backups_storage_insert'),
      migration.indexOf('backups_storage_select'),
    )
    expect(insertSection).toContain("auth.uid()::text")
    expect(insertSection).toContain('storage.foldername(name)')
  })

  it('backups SELECT enforces caller-owned path prefix', () => {
    const selectSection = migration.slice(
      migration.indexOf('backups_storage_select'),
      migration.indexOf('backups_storage_delete'),
    )
    expect(selectSection).toContain("auth.uid()::text")
  })
})

// ── Backup: explicit org scoping, not RLS-only ────────────────────────────────

describe('backupRestore explicit org scoping', () => {
  const code = src('utils/backupRestore.ts')

  it('ManagedTableConfig has orgScoped field', () => {
    expect(code).toContain('orgScoped?: boolean')
  })

  it('fetchTableData accepts optional orgId and filters', () => {
    const fnSection = code.slice(
      code.indexOf('export async function fetchTableData'),
      code.indexOf('export type BackupProgressCallback'),
    )
    expect(fnSection).toContain('orgId?: string')
    expect(fnSection).toContain("q.eq('org_id', orgId)")
  })

  it('createBackup accepts optional orgId parameter', () => {
    const fnSig = code.slice(
      code.indexOf('export async function createBackup'),
      code.indexOf('): Promise<BackupFileV2>'),
    )
    expect(fnSig).toContain('orgId?: string')
  })

  it('createBackup passes orgId to fetchTableData for orgScoped tables', () => {
    const bodySection = code.slice(
      code.indexOf('// 2. Export managed tables'),
      code.indexOf('// 3. Export unmanaged tables'),
    )
    expect(bodySection).toContain('def.orgScoped && orgId')
  })

  it('uploadBackupForLink accepts orgId and scopes storage path', () => {
    const fnSection = code.slice(
      code.indexOf('export async function uploadBackupForLink'),
      code.indexOf('// ── Validation'),
    )
    expect(fnSection).toContain('orgId?: string')
    expect(fnSection).toContain('orgSegment')
    expect(fnSection).toContain('`${userId}/${orgSegment}/')
  })

  it('all major transaction tables are orgScoped: true', () => {
    const orgScopedTables = [
      'inflow_transactions', 'outflow_transactions', 'intra_flows',
      'bank_deposits', 'intrabank_transfers', 'fx_transactions',
      'banks', 'categories', 'category_groups', 'allocation_configs',
    ]
    orgScopedTables.forEach(t => {
      const idx = code.indexOf(`key: '${t}'`)
      const block = code.slice(idx, idx + 300)
      expect(block).toContain('orgScoped: true')
    })
  })

  it('organizations is not a row-level backup/restore table', () => {
    // Instance-wide (no org_id): exporting or upserting it as a row risks
    // cross-org leakage / plan-column tampering. It must not appear in the
    // managed registry at all — org identity is captured as a scalar
    // snapshot (orgSettings) instead. (`currencies` is a normal org-scoped
    // table — see #476 — and is expected to appear with key: 'currencies'.)
    expect(code).not.toContain("key: 'organizations'")
  })
})

// ── BackupModal passes orgId ──────────────────────────────────────────────────

describe('BackupModal org scoping', () => {
  const code = src('components/modals/BackupModal.tsx')

  it('imports useOrgStore', () => {
    expect(code).toContain("from '../../store/orgStore'")
  })

  it('reads orgId from store', () => {
    expect(code).toContain('useOrgStore((s) => s.orgId)')
  })

  it('passes orgId to createBackup', () => {
    expect(code).toContain('orgId ?? undefined,')
  })

  it('passes orgId to uploadBackupForLink', () => {
    expect(code).toContain('uploadBackupForLink(backup, user.id, orgId ?? undefined)')
  })
})

// ── LB-5 / S-C2: NULL org_id prevention ──────────────────────────────────────

describe('LB-5 / S-C2: get_current_org_id() cannot silently supply NULL', () => {
  it('migration replaces get_current_org_id() with exception-raising stub', () => {
    const migration = readFileSync(
      resolve(ROOT, 'supabase/migrations/20260605000001_fix_null_org_id.sql'),
      'utf-8',
    )
    expect(migration).toContain('CREATE OR REPLACE FUNCTION public.get_current_org_id()')
    expect(migration).toContain('RAISE EXCEPTION')
    expect(migration).not.toContain('SELECT id FROM public.organizations WHERE slug')
  })

  it('migration adds NOT NULL to audit_log.org_id', () => {
    const migration = readFileSync(
      resolve(ROOT, 'supabase/migrations/20260605000001_fix_null_org_id.sql'),
      'utf-8',
    )
    expect(migration).toContain('ALTER TABLE public.audit_log')
    expect(migration).toContain('ALTER COLUMN org_id SET NOT NULL')
  })

  it('migration adds NOT NULL to field_changes.org_id', () => {
    const migration = readFileSync(
      resolve(ROOT, 'supabase/migrations/20260605000001_fix_null_org_id.sql'),
      'utf-8',
    )
    expect(migration).toContain('ALTER TABLE public.field_changes')
    expect(migration).toContain('ALTER COLUMN org_id SET NOT NULL')
  })

  it('migration backfills audit_log NULL rows before adding NOT NULL', () => {
    const migration = readFileSync(
      resolve(ROOT, 'supabase/migrations/20260605000001_fix_null_org_id.sql'),
      'utf-8',
    )
    const backfillIdx = migration.indexOf('UPDATE public.audit_log')
    const notNullIdx  = migration.indexOf("ALTER TABLE public.audit_log\n  ALTER COLUMN org_id SET NOT NULL")
    expect(backfillIdx).toBeGreaterThanOrEqual(0)
    expect(notNullIdx).toBeGreaterThan(backfillIdx)
  })
})

// LB-5 / S-C2 superseded by LB-9: audit functions are now complete no-ops
// (DB triggers are the sole writers); no conditional org_id or DB inserts exist.
describe('LB-5 / S-C2 + LB-9: audit functions make no DB calls', () => {
  const code = src('hooks/useMutations.ts')

  it('logAudit makes no DB call and uses no conditional org_id', () => {
    const section = code.slice(
      code.indexOf('async function logAudit'),
      code.indexOf('async function batchLogAudit'),
    )
    expect(section).not.toContain("supabase.from('audit_log')")
    expect(section).not.toContain("...(orgId ?")
  })

  it('logFieldChanges makes no DB call and uses no conditional org_id', () => {
    const section = code.slice(
      code.indexOf('async function logFieldChanges'),
      code.indexOf('async function logAudit'),
    )
    expect(section).not.toContain("supabase.from('field_changes')")
    expect(section).not.toContain("...(orgId ?")
  })

  it('batchLogAudit makes no DB call and uses no conditional org_id', () => {
    const section = code.slice(
      code.indexOf('async function batchLogAudit'),
      code.indexOf('async function batchLogFieldChanges'),
    )
    expect(section).not.toContain("supabase.from('audit_log')")
    expect(section).not.toContain("...(orgId ?")
  })

  it('batchLogFieldChanges makes no DB call and uses no conditional org_id', () => {
    const section = code.slice(
      code.indexOf('async function batchLogFieldChanges'),
      code.indexOf('// ── Input types'),
    )
    expect(section).not.toContain("supabase.from('field_changes')")
    expect(section).not.toContain("...(orgId ?")
  })
})

describe('LB-5 / S-C2: ImportModal always tags rows with org_id', () => {
  const code = src('components/modals/ImportModal.tsx')

  it('runImport guards on orgId before any DB work', () => {
    const runImportSection = code.slice(
      code.indexOf('const runImport = useCallback'),
      code.indexOf('setImporting(true)'),
    )
    expect(runImportSection).toMatch(/if \(!orgId\)/)
  })

  it('inflow rows always receive org_id (not conditional)', () => {
    expect(code).toContain("row.org_id = orgId")
  })

  it('FX rows no longer use conditional if(orgId) guard', () => {
    expect(code).not.toContain('if (orgId)  row.org_id')
    expect(code).not.toContain('if (orgId) row.org_id')
  })
})

describe('LB-5 / S-C2: income_type_rules always tagged with org_id', () => {
  const code = src('hooks/useIncomeTypes.ts')

  it('income_type_rules insert includes org_id', () => {
    const rulesInsertSection = code.slice(
      code.indexOf("from('income_type_rules').insert"),
      code.indexOf("from('income_type_rules').insert") + 300,
    )
    expect(rulesInsertSection).toContain('org_id')
  })

  it('saveIncomeType throws on null orgId regardless of existingId', () => {
    // Guard must fire for both create and update paths since rules insert always needs org_id
    expect(code).not.toContain('if (!existingId && !orgId)')
    const guardSection = code.slice(
      code.indexOf('const { orgId } = useOrgStore.getState()'),
      code.indexOf('const { orgId } = useOrgStore.getState()') + 100,
    )
    expect(guardSection).toContain("if (!orgId) throw new Error('No active organisation.')")
  })
})

// ── LB-2/E-C2: Atomic FX Conversion ──────────────────────────────────────────

describe('useAddFXConversion atomicity (LB-2/E-C2)', () => {
  const code = src('hooks/useFXConversions.ts')

  it('uses supabase.rpc for the conversion (single atomic call)', () => {
    expect(code).toContain("supabase.rpc('perform_fx_conversion'")
  })

  it('does not make separate insert calls for fx_transactions', () => {
    expect(code).not.toContain(".from('fx_transactions').insert(")
  })

  it('does not make separate insert calls for inflow_transactions inside useAddFXConversion', () => {
    const mutationSection = code.slice(
      code.indexOf('export function useAddFXConversion'),
      code.lastIndexOf('}'),
    )
    expect(mutationSection).not.toContain(".from('inflow_transactions').insert(")
  })

  it('does not make separate insert calls for fx_conversions', () => {
    expect(code).not.toContain(".from('fx_conversions').insert(")
  })

  it('passes p_org_id to RPC', () => {
    expect(code).toContain('p_org_id:')
  })

  it('passes p_bank_name to RPC (required for BankLedger visibility)', () => {
    expect(code).toContain('p_bank_name:')
  })
})

// ── LB-11 / SC-H1: server-side pagination + export org scoping ────────────────

describe('LB-11: export functions include org_id filter (Inflows)', () => {
  const code = src('pages/Inflows.tsx')

  it('imports useOrgStore', () => {
    expect(code).toContain("from '../store/orgStore'")
  })

  it('imports fetchAllPaginated utility', () => {
    expect(code).toContain('fetchAllPaginated')
  })

  it('handleExportAll filters by org_id', () => {
    const exportSection = code.slice(
      code.indexOf('handleExportAll'),
      code.indexOf('handleExportAll') + 2000,
    )
    expect(exportSection).toContain(".eq('org_id', orgId)")
  })

  it('handleExportAll does not use raw .limit(10000)', () => {
    expect(code).not.toContain('.limit(10000)')
  })
})

describe('LB-11: export functions include org_id filter (Outflows)', () => {
  const code = src('pages/Outflows.tsx')

  it('imports useOrgStore', () => {
    expect(code).toContain("from '../store/orgStore'")
  })

  it('imports fetchAllPaginated utility', () => {
    expect(code).toContain('fetchAllPaginated')
  })

  it('handleExportAll filters by org_id', () => {
    const exportSection = code.slice(
      code.indexOf('handleExportAll'),
      code.indexOf('handleExportAll') + 2000,
    )
    expect(exportSection).toContain(".eq('org_id', orgId)")
  })

  it('handleExportAll does not use raw .limit(10000)', () => {
    expect(code).not.toContain('.limit(10000)')
  })

  it('outflow_type_id filter is passed to hook (server-side), not applied client-side', () => {
    expect(code).toContain('outflowTypeId:')
    expect(code).not.toContain("data.filter(r => r.outflow_type_id")
  })
})

describe('LB-11: export functions include org_id filter (PendingDeductions)', () => {
  const code = src('pages/PendingDeductions.tsx')

  it('imports useOrgStore', () => {
    expect(code).toContain("from '../store/orgStore'")
  })

  it('imports fetchAllPaginated utility', () => {
    expect(code).toContain('fetchAllPaginated')
  })

  it('handleExportAll filters by org_id', () => {
    const exportSection = code.slice(
      code.indexOf('handleExportAll'),
      code.indexOf('handleExportAll') + 1500,
    )
    expect(exportSection).toContain(".eq('org_id', orgId)")
  })

  it('handleExportAll does not use raw .limit(10000)', () => {
    expect(code).not.toContain('.limit(10000)')
  })
})

describe('LB-11: RefundTransactions scoped to org and limited', () => {
  const code = src('pages/RefundTransactions.tsx')

  it('imports useOrgStore', () => {
    expect(code).toContain("from '../store/orgStore'")
  })

  it('load() guards on orgId', () => {
    expect(code).toContain('if (!orgId)')
  })

  it('both queries in load() filter by org_id', () => {
    const loadSection = code.slice(
      code.indexOf('const load = async'),
      code.indexOf('const handleEdit'),
    )
    const orgIdOccurrences = (loadSection.match(/\.eq\('org_id', orgId\)/g) ?? []).length
    expect(orgIdOccurrences).toBeGreaterThanOrEqual(2)
  })

  it('both queries apply a safety limit', () => {
    const loadSection = code.slice(
      code.indexOf('const load = async'),
      code.indexOf('const handleEdit'),
    )
    const limitOccurrences = (loadSection.match(/\.limit\(/g) ?? []).length
    expect(limitOccurrences).toBeGreaterThanOrEqual(2)
  })

  it('shows truncation banner when limit is hit', () => {
    expect(code).toContain('truncated')
    expect(code).toContain('REFUND_LIMIT')
  })
})

describe('LB-11: ReversalTransactions scoped to org and limited', () => {
  const code = src('pages/ReversalTransactions.tsx')

  it('imports useOrgStore', () => {
    expect(code).toContain("from '../store/orgStore'")
  })

  it('load() guards on orgId', () => {
    expect(code).toContain('if (!orgId)')
  })

  it('both queries in load() filter by org_id', () => {
    const start = code.indexOf('const load = async')
    const loadSection = code.slice(start, start + 3000)
    const orgIdOccurrences = (loadSection.match(/\.eq\('org_id', orgId\)/g) ?? []).length
    expect(orgIdOccurrences).toBeGreaterThanOrEqual(2)
  })

  it('both queries apply a safety limit', () => {
    const start = code.indexOf('const load = async')
    const loadSection = code.slice(start, start + 3000)
    const limitOccurrences = (loadSection.match(/\.limit\(/g) ?? []).length
    expect(limitOccurrences).toBeGreaterThanOrEqual(2)
  })

  it('shows truncation banner when limit is hit', () => {
    expect(code).toContain('truncated')
    expect(code).toContain('REVERSAL_LIMIT')
  })
})

describe('LB-11: BankDeposits scoped to org in load() and loadRecon()', () => {
  const code = src('pages/BankMovement.tsx')

  it('uses useOrgStore hook in main component', () => {
    const mainComponent = code.slice(code.indexOf('export default function BankMovement'))
    expect(mainComponent).toContain("useOrgStore((s) => s.orgId)")
  })

  it('load() guards on orgId', () => {
    const loadFn = code.slice(
      code.indexOf('const load = useCallback'),
      code.indexOf('}, [orgId])'),
    )
    expect(loadFn).toContain('if (!orgId)')
  })

  it('bank_deposits query in load() filters by org_id', () => {
    const loadFn = code.slice(
      code.indexOf('const load = useCallback'),
      code.indexOf('}, [orgId])'),
    )
    expect(loadFn).toContain(".eq('org_id', orgId)")
  })

  it('inflow/outflow queries in load() filter by org_id', () => {
    const loadFn = code.slice(
      code.indexOf('const load = useCallback'),
      code.indexOf('}, [orgId])'),
    )
    const orgIdOccurrences = (loadFn.match(/\.eq\('org_id', orgId\)/g) ?? []).length
    expect(orgIdOccurrences).toBeGreaterThanOrEqual(3)
  })

  it('loadRecon() guards on orgId', () => {
    const reconFn = code.slice(
      code.indexOf('const loadRecon = async'),
      code.indexOf('const toggleRecon'),
    )
    expect(reconFn).toContain('if (!orgId)')
    expect(reconFn).toContain(".eq('org_id', orgId)")
  })
})

describe('LB-11: useOutflowTransactions supports server-side outflowTypeId filter', () => {
  const code = src('hooks/useTransactions.ts')

  it('TransactionFilters includes outflowTypeId', () => {
    expect(code).toContain('outflowTypeId?: string')
  })

  it('applies outflow_type_id filter to query', () => {
    expect(code).toContain(".eq('outflow_type_id', outflowTypeId)")
  })

  it('outflowTypeId is in useCallback dependencies', () => {
    const outflowHook = code.slice(
      code.indexOf('export function useOutflowTransactions'),
      code.indexOf('// ── useIntraFlows'),
    )
    expect(outflowHook).toContain('outflowTypeId')
  })
})

// ── Reports: department breakdown org scoping ────────────────────────────────

describe('Reports DepartmentBreakdownPanel org scoping', () => {
  const code = src('pages/Reports.tsx')
  const panel = code.slice(
    code.indexOf('function DepartmentBreakdownPanel'),
    code.indexOf('function FXHoldingsPanel'),
  )

  it('panel reads orgId from the org store', () => {
    expect(panel).toContain('useOrgStore(s => s.orgId)')
  })

  it('every outflow_transactions query in the panel filters by org_id', () => {
    const queries = (panel.match(/\.from\('outflow_transactions'\)/g) ?? []).length
    const filters = (panel.match(/\.eq\('org_id', orgId\)/g) ?? []).length
    expect(queries).toBeGreaterThanOrEqual(3)
    expect(filters).toBe(queries)
  })

  it('summary, drill-down and cross-filter loaders guard on orgId', () => {
    expect(panel).toContain('if (!orgId) { setRows([]); setLoading(false); return }')
    expect(panel).toContain('if (!orgId) { setDrillTxns([]); return }')
    expect(panel).toContain('if (!orgId || (!filterDeptId && !filterTypeId))')
  })

  it('orgId is in the loader useCallback dependencies', () => {
    expect(panel).toContain('[filter.range, departments, orgId]')
    expect(panel).toContain('[filter.range, orgId]')
    expect(panel).toContain('[filterDeptId, filterTypeId, filter.range, orgId]')
  })
})

describe('useReportEngine category_opening_balances org scoping', () => {
  const code = src('hooks/useReportEngine.ts')

  it('category_opening_balances query filters by org_id', () => {
    const idx = code.indexOf(".from('category_opening_balances')")
    expect(idx).toBeGreaterThanOrEqual(0)
    expect(code.slice(idx, idx + 200)).toContain(".eq('org_id', orgId)")
  })

  it('no report-engine query is left unscoped', () => {
    const fetchSection = code.slice(
      code.indexOf('const load'),
      code.indexOf('}, [orgId, reportDate'),
    )
    const queries = (fetchSection.match(/\.from\('/g) ?? []).length
    const filters = (fetchSection.match(/\.eq\('org_id', orgId\)/g) ?? []).length
    expect(filters).toBe(queries)
  })
})

// ── Unique organisation names ────────────────────────────────────────────────

describe('unique organisation name migration', () => {
  const migration = readFileSync(
    resolve(ROOT, 'supabase/migrations/20260803000001_unique_organization_name.sql'),
    'utf-8',
  )

  it('adds an IMMUTABLE normalisation helper', () => {
    expect(migration).toContain('CREATE OR REPLACE FUNCTION public.normalize_org_name(p_name text)')
    expect(migration).toContain('IMMUTABLE')
  })

  it('de-duplicates existing names before creating the index', () => {
    const dedupeIdx = migration.indexOf('UPDATE public.organizations')
    const indexIdx  = migration.indexOf('CREATE UNIQUE INDEX IF NOT EXISTS organizations_name_unique')
    expect(dedupeIdx).toBeGreaterThanOrEqual(0)
    expect(indexIdx).toBeGreaterThan(dedupeIdx)
  })

  it('creates a case-insensitive unique index excluding pending deletions', () => {
    expect(migration).toContain('CREATE UNIQUE INDEX IF NOT EXISTS organizations_name_unique')
    expect(migration).toContain('public.normalize_org_name(name)')
    expect(migration).toContain("WHERE status <> 'pending_deletion'")
  })

  it('create_organization rejects duplicate names with a readable error', () => {
    expect(migration).toContain('CREATE OR REPLACE FUNCTION public.create_organization(p_name text)')
    expect(migration).toContain('already exists. Please choose a different name.')
  })

  it('slug retry loop no longer swallows name collisions', () => {
    expect(migration).toContain('GET STACKED DIAGNOSTICS')
    expect(migration).toContain("v_constraint = 'organizations_name_unique'")
  })

  it('create_organization keeps a search_path guard', () => {
    expect(migration).toContain('SET search_path = public')
  })
})

describe('unique organisation name in schema.sql', () => {
  const schema = readFileSync(resolve(ROOT, 'supabase/schema.sql'), 'utf-8')

  it('declares normalize_org_name before the unique index', () => {
    const fnIdx    = schema.indexOf('create or replace function public.normalize_org_name')
    const indexIdx = schema.indexOf('create unique index if not exists organizations_name_unique')
    expect(fnIdx).toBeGreaterThanOrEqual(0)
    expect(indexIdx).toBeGreaterThan(fnIdx)
  })

  it('create_organization pre-checks the name', () => {
    const fn = schema.slice(
      schema.indexOf('create or replace function public.create_organization'),
      schema.indexOf('grant execute on function public.create_organization'),
    )
    expect(fn).toContain('public.normalize_org_name(v_name)')
    expect(fn).toContain('already exists. Please choose a different name.')
  })
})

describe('LB-11: paginatedExport utility prevents silent truncation', () => {
  const code = src('utils/paginatedExport.ts')

  it('exports EXPORT_MAX constant', () => {
    expect(code).toContain('export const EXPORT_MAX')
  })

  it('exports fetchAllPaginated function', () => {
    expect(code).toContain('export async function fetchAllPaginated')
  })

  it('throws on error instead of silently returning empty', () => {
    expect(code).toContain('throw new Error')
  })

  it('returns truncated flag so callers can warn users', () => {
    expect(code).toContain('truncated')
  })
})
