-- ============================================================
-- SECURITY FIX: Org isolation for Supabase Storage buckets
--
-- Findings:
--   1. receipts bucket policies used auth.uid() IS NOT NULL only —
--      any authenticated user could read/write any file regardless of org.
--   2. backups bucket had no storage RLS policies at all.
--   3. Receipt paths had no org prefix, so path-guessing bypassed DB RLS.
--
-- New path conventions enforced here:
--   receipts  → {orgId}/{entityType}/{entityId}/{filename}
--   backups   → {userId}/{orgId}/backup-{date}-{ts}.json
--
-- Storage policies extract the first path segment as orgId and verify
-- the caller is an active member of that org. The backups bucket
-- additionally requires the path's first segment to be the caller's uid.
--
-- NOTE: Existing receipt files stored under the old path pattern
-- (entityType/entityId/filename) are still accessible via signed URLs
-- generated by the application. Old paths cannot pass the new INSERT
-- policy, so new uploads will always use the org-prefixed path.
-- ============================================================

-- ── receipts bucket: ensure it exists and is private ─────────────────────────

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'receipts', 'receipts', false,
  20971520,   -- 20 MB per file
  ARRAY['image/jpeg','image/png','image/gif','image/webp','application/pdf',
        'image/heic','image/heif','image/tiff']
)
ON CONFLICT (id) DO UPDATE
  SET public            = false,
      file_size_limit   = EXCLUDED.file_size_limit;

-- ── backups bucket: ensure it exists and is private ──────────────────────────

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'backups', 'backups', false,
  524288000,  -- 500 MB per backup
  ARRAY['application/json']
)
ON CONFLICT (id) DO UPDATE
  SET public = false;

-- ── Drop all old receipts storage policies ────────────────────────────────────

DROP POLICY IF EXISTS "receipts_objects_insert" ON storage.objects;
DROP POLICY IF EXISTS "receipts_objects_select" ON storage.objects;
DROP POLICY IF EXISTS "receipts_objects_delete" ON storage.objects;
DROP POLICY IF EXISTS "receipts_objects_update" ON storage.objects;

-- Legacy policy names from pre-migration SQL embedded in ReceiptBadge component
DROP POLICY IF EXISTS "receipts_objects_read"   ON storage.objects;
DROP POLICY IF EXISTS "receipts_objects_write"  ON storage.objects;

-- ── New receipts storage policies: org-prefix-aware ──────────────────────────
-- Path format: {orgId}/{entityType}/{entityId}/{filename}
-- The first path segment is the orgId. We verify the caller is an active member.

CREATE POLICY "receipts_storage_insert" ON storage.objects
  FOR INSERT WITH CHECK (
    bucket_id = 'receipts'
    AND auth.uid() IS NOT NULL
    AND (storage.foldername(name))[1] IS NOT NULL
    AND public.is_org_member((storage.foldername(name))[1]::uuid)
    AND public.is_org_finance_user((storage.foldername(name))[1]::uuid)
  );

CREATE POLICY "receipts_storage_select" ON storage.objects
  FOR SELECT USING (
    bucket_id = 'receipts'
    AND auth.uid() IS NOT NULL
    AND (storage.foldername(name))[1] IS NOT NULL
    AND public.is_org_member((storage.foldername(name))[1]::uuid)
  );

CREATE POLICY "receipts_storage_delete" ON storage.objects
  FOR DELETE USING (
    bucket_id = 'receipts'
    AND auth.uid() IS NOT NULL
    AND (storage.foldername(name))[1] IS NOT NULL
    AND public.is_org_finance_user((storage.foldername(name))[1]::uuid)
  );

CREATE POLICY "receipts_storage_update" ON storage.objects
  FOR UPDATE USING (
    bucket_id = 'receipts'
    AND auth.uid() IS NOT NULL
    AND (storage.foldername(name))[1] IS NOT NULL
    AND public.is_org_finance_user((storage.foldername(name))[1]::uuid)
  );

-- ── Drop all old backups storage policies ─────────────────────────────────────

DROP POLICY IF EXISTS "backups_objects_insert" ON storage.objects;
DROP POLICY IF EXISTS "backups_objects_select" ON storage.objects;
DROP POLICY IF EXISTS "backups_objects_delete" ON storage.objects;
DROP POLICY IF EXISTS "backups_objects_update" ON storage.objects;

-- ── New backups storage policies: user-prefix-scoped ─────────────────────────
-- Path format: {userId}/{orgId}/backup-{date}-{ts}.json
-- First segment must be the caller's own user id.

CREATE POLICY "backups_storage_insert" ON storage.objects
  FOR INSERT WITH CHECK (
    bucket_id = 'backups'
    AND auth.uid() IS NOT NULL
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

CREATE POLICY "backups_storage_select" ON storage.objects
  FOR SELECT USING (
    bucket_id = 'backups'
    AND auth.uid() IS NOT NULL
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

CREATE POLICY "backups_storage_delete" ON storage.objects
  FOR DELETE USING (
    bucket_id = 'backups'
    AND auth.uid() IS NOT NULL
    AND (storage.foldername(name))[1] = auth.uid()::text
  );
